# fly.toml app configuration file generated for waspblog-client on 2024-11-16T08:53:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'waspblog-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
